on: issue_comment
jobs:
  set_input:
    name: Set some input
    runs-on: linux-latest
    steps:
      - name: Set some input
        id: passthru
        uses: GrubhubProd/spike-feci-actions/passthru@v1
        with:
          in: 'This is my message!'
      - name: Get the output
        run: echo "The message was ${{ steps.passthru.outputs.out }}"

