name: Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: The version of the release
        required: true
jobs:
  release:
    name: Release
    runs-on: [ubuntu-latest]
    steps:
      - name: Identify Ourselves
        run: |
          git config --global user.email "robb.oliver@gmail.com"
          git config --global user.name "logicblue"
      - name: Check Out
        uses: actions/checkout@v2
      - name: Create release branch
        run: |
          git checkout -b release/${{ github.event.inputs.release_version }}
          echo "${{ github.event.inputs.release_version }}" > version.txt
          git add .
          git commit -m 'Releasing version ${{ github.event.inputs.release_version }}'
          git push origin release/${{ github.event.inputs.release_version }}
      - name: Worflow Dispatch
        uses: benc-uk/workflow-dispatch@v1.1
        with:
          workflow: Distribute
          ref: release/${{ github.event.inputs.release_version }}
          token: ${{ secrets.RKO_ACTIONS_TOKEN }}
